" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vim_runtime/my_configs.vim

set runtimepath+=~/.vim_runtime
call plug#begin('~/.vim/plugged')
source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/filetypes.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
source ~/.vim_runtime/vimrcs/extended.vim
try
  source ~/.vim_runtime/my_configs.vim
catch
endtry
Plug 'mxw/vim-jsx'
Plug 'hacksoftware/vim-python-domain-knowledge'
Plug 'isruslan/vim-es6'
Plug 'neoclide/coc-css'
Plug 'josa42/coc-sh'
call plug#end()
